/**
 * License audit + report generator for production dependencies.
 *
 * Bun uses an isolated `node_modules` layout (symlinks into `.bun/`), so
 * `license-checker-rseidelsohn` only sees a workspace's deps when invoked from
 * inside that workspace. This script walks each workspace listed under the
 * root `package.json` `workspaces` field, spawns the checker in parallel with
 * `--onlyAllow` (permissive-only policy) and `--json`, collects all violations
 * before exiting, and on a clean pass writes a deterministic `LICENSES.md`
 * (committed) so PRs that change deps without regenerating it surface in CI
 * via `git diff --exit-code`.
 *
 * Invoked from `bun run licenses:audit`.
 *
 * @see https://github.com/RSeidelsohn/license-checker-rseidelsohn
 */
import { readFile, readdir, rename } from "node:fs/promises";
import { join } from "node:path";

interface LicenseEntry {
  licenses: string | string[];
  repository?: string;
  publisher?: string;
}

interface AuditResult {
  dir: string;
  exitCode: number;
  stderr: string;
  report: Record<string, LicenseEntry> | null;
}

const allowedLicenses = "MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC;CC0-1.0;0BSD;Unlicense";
const outputPath = "LICENSES.md";
const tmpPath = `${outputPath}.tmp`;
const timeoutMs = 60_000;

const escapeCell = (value: string): string => value.replace(/\|/g, "\\|");

const renderMarkdown = (report: Record<string, LicenseEntry>, workspaceCount: number): string => {
  const rows = Object.entries(report)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([pkg, entry]) => {
      const license = Array.isArray(entry.licenses) ? entry.licenses.join(", ") : entry.licenses;
      const repo = entry.repository ?? "";
      return `| ${escapeCell(pkg)} | ${escapeCell(license)} | ${escapeCell(repo)} |`;
    });
  return [
    "<!-- generated by scripts/licenses-report.ts; do not edit -->",
    "",
    "# Third-party licenses",
    "",
    `${Object.keys(report).length} unique production dependencies across ${workspaceCount} workspaces. Regenerate with \`bun run licenses:audit\`.`,
    "",
    "| Package | License | Repository |",
    "| --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
};

const isMissingPathError = (err: unknown): boolean =>
  err instanceof Error && "code" in err && (err.code === "ENOENT" || err.code === "ENOTDIR");

const readdirIfPresent = async (path: string): Promise<string[]> => {
  try {
    return await readdir(path);
  } catch (err) {
    if (isMissingPathError(err)) return [];
    throw err;
  }
};

const expandWorkspaceCandidates = async (patterns: string[]): Promise<string[]> => {
  const candidates: string[] = [];
  for (const pattern of patterns) {
    const match = pattern.match(/^(.+)\/\*$/);
    if (!match) continue;
    const [, root] = match;
    const entries = await readdirIfPresent(root);
    for (const entry of entries) candidates.push(join(root, entry));
  }
  return candidates;
};

const hasProductionDeps = async (dir: string): Promise<boolean> => {
  try {
    const pkg = JSON.parse(await readFile(join(dir, "package.json"), "utf8")) as {
      dependencies?: Record<string, string>;
    };
    return Boolean(pkg.dependencies && Object.keys(pkg.dependencies).length > 0);
  } catch (err) {
    if (isMissingPathError(err)) return false;
    throw err;
  }
};

const findProductionWorkspaces = async (): Promise<string[]> => {
  const rootPkg = JSON.parse(await readFile("package.json", "utf8")) as { workspaces?: string[] };
  const candidates = await expandWorkspaceCandidates(rootPkg.workspaces ?? []);
  const checks = await Promise.all(
    candidates.map(async (dir) => ((await hasProductionDeps(dir)) ? dir : null))
  );
  return checks.filter((d): d is string => d !== null);
};

const auditWorkspace = async (dir: string): Promise<AuditResult> => {
  const proc = Bun.spawn({
    cmd: [
      "bunx",
      "--bun",
      "license-checker-rseidelsohn",
      "--production",
      "--excludePrivatePackages",
      "--json",
      `--onlyAllow=${allowedLicenses}`,
    ],
    cwd: dir,
    stdout: "pipe",
    stderr: "pipe",
  });
  const timer = setTimeout(() => proc.kill(), timeoutMs);
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  clearTimeout(timer);
  if (exitCode !== 0) {
    return { dir, exitCode: exitCode ?? 1, stderr, report: null };
  }
  try {
    return { dir, exitCode: 0, stderr: "", report: JSON.parse(stdout) };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { dir, exitCode: 1, stderr: `JSON parse error: ${message}\n`, report: null };
  }
};

const reportViolations = (violations: AuditResult[]): void => {
  for (const v of violations) {
    process.stderr.write(`[licenses] policy violation in ${v.dir}:\n${v.stderr}\n`);
  }
};

const aggregateReports = (results: AuditResult[]): Record<string, LicenseEntry> => {
  const aggregate: Record<string, LicenseEntry> = {};
  for (const r of results) {
    if (r.report) Object.assign(aggregate, r.report);
  }
  return aggregate;
};

const main = async (): Promise<void> => {
  const dirs = await findProductionWorkspaces();
  if (dirs.length === 0) {
    process.stderr.write("[licenses] no workspaces with production dependencies\n");
    process.exitCode = 1;
    return;
  }
  const results = await Promise.all(dirs.map(auditWorkspace));
  const violations = results.filter((r) => r.exitCode !== 0);
  if (violations.length > 0) {
    reportViolations(violations);
    process.exitCode = 1;
    return;
  }
  const aggregate = aggregateReports(results);
  await Bun.write(tmpPath, renderMarkdown(aggregate, dirs.length));
  await rename(tmpPath, outputPath);
  process.stdout.write(
    `[licenses] wrote ${outputPath} (${Object.keys(aggregate).length} packages across ${dirs.length} workspaces)\n`
  );
};

await main();
